// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sucursal.Infraestructura.Data;

#nullable disable

namespace Sucursal.Migrations
{
    [DbContext(typeof(SucursalDbContext))]
    [Migration("20251123140810_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sucursal.Core.Entidades.GerenteSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal");

                    b.ToTable("GerentesSucursal");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.ItemSolicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdSolicitud")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("ItemsSolicitud");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.ReporteDiarioConsolidado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CampanasActivas")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadClientes")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEmpleadosAusentes")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEmpleadosPresentes")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadProductosVendidos")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadTransacciones")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostoInventarioDia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostoLaboralDia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostoMarketingDia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostoOperativoDia")
                        .HasColumnType("numeric");

                    b.Property<string>("DetallesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoConsolidacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaConsolidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NominaDelDia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PorcentajeUtilidadBruta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PresupuestoGastadoMarketing")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductosDevueltos")
                        .HasColumnType("integer");

                    b.Property<int>("ProductosVencidos")
                        .HasColumnType("integer");

                    b.Property<decimal>("StockValorado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVentasProductos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVentasServicios")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal", "Fecha");

                    b.ToTable("ReportesDiarios");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.SolicitudInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CIAprobador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CISolicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetallesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoSolicitado")
                        .HasColumnType("numeric");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal", "Estado");

                    b.ToTable("SolicitudesInternas");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.SucursalEntidad", b =>
                {
                    b.Property<string>("CodigoSucursal")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoraApertura")
                        .HasColumnType("integer");

                    b.Property<int>("HoraCierre")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.GerenteSucursal", b =>
                {
                    b.HasOne("Sucursal.Core.Entidades.SucursalEntidad", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodigoSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.ItemSolicitud", b =>
                {
                    b.HasOne("Sucursal.Core.Entidades.SolicitudInterna", "Solicitud")
                        .WithMany("Items")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.ReporteDiarioConsolidado", b =>
                {
                    b.HasOne("Sucursal.Core.Entidades.SucursalEntidad", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodigoSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.SolicitudInterna", b =>
                {
                    b.HasOne("Sucursal.Core.Entidades.SucursalEntidad", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodigoSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Sucursal.Core.Entidades.SolicitudInterna", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
